name: "Build, Test, and Push to ECR"
description: "A custom GitHub Action for building, testing, and pushing Docker images to Amazon ECR"
author: "NaviTech Solutions"

inputs:
  aws-region:
    description: "AWS region"
    required: true
    default: "ap-east-1"
  branch-name:
    description: "Branch name"
    required: true
  aws-access-key-id:
    description: "AWS Access Key ID"
    required: true
    default: ""
  aws-secret-access-key:
    description: "AWS Secret Access Key"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - name: Setup environment variables
      run: ./setup.sh ${{ inputs.branch-name }}
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Create ECR repository
      uses: int128/create-ecr-repository-action@v1.325.0
      with:
        repository: ${{ env.ECR_REPOSITORY }}
        public: false

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
      with:
        region: ${{ inputs.aws-region }}

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3.7.1
      with:
        driver: docker-container
        driver-opts: network=host

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6.9.0
      with:
        context: .
        file: .gitea/workflows/Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
