name: Build, Test, and Push to ECR

on:
  push:
    branches:
      - master
      - develop

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Run custom CI action
        uses: NaviTech-Solutions/ci@main
        with:
          aws-region: "ap-east-1"
          branch-name: ${{ github.ref_name }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
